// Base d'objets magiques D&D 5e (fr) — source : aidedd.org
// Format : [nom, rareté, type]
// Raretés : C=Commun, PC=Peu commun, R=Rare, TR=Très rare, L=Légendaire, A=Artéfact, V=Variable
// Types   : ARM=Armure, ARW=Arme, BAG=Baguette, BAT=Bâton, SCE=Sceptre, ANN=Anneau, OM=Obj. merveilleux, POT=Potion, PAR=Parchemin

const ITEMS_DB = [
  // Amulettes / Anneaux
  ["Amulette d'antidétection","PC","OM"],
  ["Amulette de bonne santé","R","OM"],
  ["Amulette de cicatrisation","PC","OM"],
  ["Amulette de protection contre le poison","R","OM"],
  ["Amulette de santé","PC","OM"],
  ["Amulette de sombre éclat","C","OM"],
  ["Amulette des plans","TR","OM"],
  ["Amulette mécanique","C","OM"],
  ["Anneau d'action libre","R","ANN"],
  ["Anneau d'esquive totale","R","ANN"],
  ["Anneau d'influence sur les animaux","R","ANN"],
  ["Anneau d'invisibilité","L","ANN"],
  ["Anneau de barrière mentale","PC","ANN"],
  ["Anneau de chaleur constante","PC","ANN"],
  ["Anneau de contrôle des élémentaires","L","ANN"],
  ["Anneau de convocation de djinn","L","ANN"],
  ["Anneau de feu d'étoiles","TR","ANN"],
  ["Anneau de feuille morte","R","ANN"],
  ["Anneau de marche sur l'eau","PC","ANN"],
  ["Anneau de nage","PC","ANN"],
  ["Anneau de protection","R","ANN"],
  ["Anneau de rayons X","R","ANN"],
  ["Anneau de régénération","TR","ANN"],
  ["Anneau de renvoi des sorts","L","ANN"],
  ["Anneau de résistance","R","ANN"],
  ["Anneau de résistance au poison","R","ANN"],
  ["Anneau de saut","PC","ANN"],
  ["Anneau de stockage de sort","R","ANN"],
  ["Anneau de télékinésie","TR","ANN"],
  ["Anneau de triple souhait","L","ANN"],
  ["Anneau du bélier","R","ANN"],
  // Armes
  ["Arc du serment","TR","ARW"],
  ["Arme +1, +2 ou +3","V","ARW"],
  ["Arme vicieuse","R","ARW"],
  ["Arme vigilante","PC","ARW"],
  ["Cimeterre de rapidité","TR","ARW"],
  ["Dague venimeuse","R","ARW"],
  ["Déluge","L","ARW"],
  ["Épée acérée","TR","ARW"],
  ["Épée ardente","R","ARW"],
  ["Épée dansante","TR","ARW"],
  ["Épée de Kas","A","ARW"],
  ["Épée de lumière lunaire","C","ARW"],
  ["Épée de réponse","L","ARW"],
  ["Épée mordante","R","ARW"],
  ["Épée radieuse","R","ARW"],
  ["Épée vengeresse","PC","ARW"],
  ["Épée voleuse de vie","R","ARW"],
  ["Épée vorpale","L","ARW"],
  ["Fer gelé","TR","ARW"],
  ["Flèche incassable","C","ARW"],
  ["Flèche tueuse","TR","ARW"],
  ["Gardienne","L","ARW"],
  ["Hache des seigneurs nains","A","ARW"],
  ["Hache du berserker","R","ARW"],
  ["Javeline de foudre","PC","ARW"],
  ["Lame porte-bonheur","L","ARW"],
  ["Lamelune","L","ARW"],
  ["Marteau de lancer nain","TR","ARW"],
  ["Marteau de tonnerre","L","ARW"],
  ["Masse d'anéantissement","R","ARW"],
  ["Masse destructrice","R","ARW"],
  ["Masse terrifiante","R","ARW"],
  ["Munition +1, +2 ou +3","V","ARW"],
  ["Munition percutante","C","ARW"],
  ["Noir rasoir","L","ARW"],
  ["Trident de domination aquatique","PC","ARW"],
  ["Tueuse de dragons","R","ARW"],
  ["Tueuse de géants","R","ARW"],
  ["Vengeresse sacrée","L","ARW"],
  ["Voleuse des neuf vies","TR","ARW"],
  // Armures
  ["Armure +1, +2 ou +3","V","ARM"],
  ["Armure d'adamantium","PC","ARM"],
  ["Armure d'écailles de dragon","TR","ARM"],
  ["Armure d'invulnérabilité","L","ARM"],
  ["Armure de cuir clouté enchantée","R","ARM"],
  ["Armure de matelot","PC","ARM"],
  ["Armure de mithral","PC","ARM"],
  ["Armure de résistance","R","ARM"],
  ["Armure de vulnérabilité","R","ARM"],
  ["Armure démoniaque","TR","ARM"],
  ["Armure fumante","C","ARM"],
  ["Armure rapide","C","ARM"],
  ["Armure rutilante","C","ARM"],
  ["Bouclier +1, +2 ou +3","V","ARM"],
  ["Bouclier animé","TR","ARM"],
  ["Bouclier antiprojectiles","R","ARM"],
  ["Bouclier d'attraction des projectiles","R","ARM"],
  ["Bouclier expressif","C","ARM"],
  ["Bouclier gardesort","TR","ARM"],
  ["Bouclier sentinelle","PC","ARM"],
  ["Harnois éthéré","L","ARM"],
  ["Harnois nain","TR","ARM"],
  ["Mailles éfrit","L","ARM"],
  ["Mailles elfiques","R","ARM"],
  // Baguettes
  ["Baguette d'éclairs","R","BAG"],
  ["Baguette d'Orcus","A","BAG"],
  ["Baguette de boules de feu","R","BAG"],
  ["Baguette de chef d'orchestre","C","BAG"],
  ["Baguette de détection de l'ennemi","R","BAG"],
  ["Baguette de détection de la magie","PC","BAG"],
  ["Baguette de métamorphose","TR","BAG"],
  ["Baguette de paralysie","R","BAG"],
  ["Baguette de peur","R","BAG"],
  ["Baguette de projectiles magiques","PC","BAG"],
  ["Baguette de pyrotechnicien","C","BAG"],
  ["Baguette de toile d'araignée","PC","BAG"],
  ["Baguette des entraves","R","BAG"],
  ["Baguette des merveilles","R","BAG"],
  ["Baguette des secrets","PC","BAG"],
  ["Baguette du grincheux","C","BAG"],
  ["Baguette du jovial","C","BAG"],
  ["Baguette du mage de guerre +1, +2 ou +3","V","BAG"],
  // Bâtons
  ["Bâton d'envoûtement","R","BAT"],
  ["Bâton de feu","TR","BAT"],
  ["Bâton de flétrissement","R","BAT"],
  ["Bâton de givre","TR","BAT"],
  ["Bâton de grand essaim","R","BAT"],
  ["Bâton de guérison","R","BAT"],
  ["Bâton de la vipère","PC","BAT"],
  ["Bâton de surpuissance","TR","BAT"],
  ["Bâton de tonnerre et de foudre","TR","BAT"],
  ["Bâton des chants d'oiseaux","C","BAT"],
  ["Bâton des forêts","R","BAT"],
  ["Bâton du python","PC","BAT"],
  ["Bâton du thaumaturge","L","BAT"],
  ["Bâton floral","C","BAT"],
  ["Bâton orné","C","BAT"],
  ["Bâton percussif","TR","BAT"],
  // Sceptres
  ["Sceptre d'absorption","TR","SCE"],
  ["Sceptre de puissance seigneuriale","L","SCE"],
  ["Sceptre de résurrection","L","SCE"],
  ["Sceptre de sécurité","TR","SCE"],
  ["Sceptre de suzeraineté","R","SCE"],
  ["Sceptre de vigilance","TR","SCE"],
  ["Sceptre du gardien des pactes","V","SCE"],
  ["Sceptre inamovible","PC","SCE"],
  ["Sceptre tentacule","R","SCE"],
  // Potions
  ["Élixir de jouvence","TR","POT"],
  ["Élixir de santé","R","POT"],
  ["Huile d'affûtage","TR","POT"],
  ["Huile d'insaisissabilité","PC","POT"],
  ["Huile éthérée","R","POT"],
  ["Philtre d'amour","PC","POT"],
  ["Potion d'agrandissement","PC","POT"],
  ["Potion d'amitié avec les animaux","PC","POT"],
  ["Potion d'escalade","C","POT"],
  ["Potion d'héroïsme","R","POT"],
  ["Potion d'invisibilité","TR","POT"],
  ["Potion d'invulnérabilité","R","POT"],
  ["Potion de clairvoyance","R","POT"],
  ["Potion de diminution","R","POT"],
  ["Potion de force de géant","V","POT"],
  ["Potion de forme gazeuse","R","POT"],
  ["Potion de guérison","V","POT"],
  ["Potion de lecture des pensées","R","POT"],
  ["Potion de poison","PC","POT"],
  ["Potion de résistance","PC","POT"],
  ["Potion de respiration aquatique","PC","POT"],
  ["Potion de souffle enflammé","PC","POT"],
  ["Potion de vitalité","TR","POT"],
  ["Potion de vitesse","TR","POT"],
  ["Potion de vol","TR","POT"],
  // Parchemins
  ["Parchemin de protection","R","PAR"],
  ["Parchemin de sort","V","PAR"],
  // Objets merveilleux
  ["Balai volant","PC","OM"],
  ["Bandeau d'intelligence","PC","OM"],
  ["Bateau pliable","R","OM"],
  ["Baume de Keoghtom","PC","OM"],
  ["Bottes ailées","PC","OM"],
  ["Bottes d'empreintes factices","C","OM"],
  ["Bottes de lévitation","R","OM"],
  ["Bottes de rapidité","R","OM"],
  ["Bottes de sept lieues","PC","OM"],
  ["Bottes des terres gelées","PC","OM"],
  ["Bottes elfiques","PC","OM"],
  ["Boule de cristal","V","OM"],
  ["Bourse à épices magique d'Heward","C","OM"],
  ["Bouteille de l'éfrit","TR","OM"],
  ["Bouteille fumigène","PC","OM"],
  ["Bracelets d'archer","PC","OM"],
  ["Bracelets de défense","R","OM"],
  ["Brasero de contrôle des élémentaires du feu","R","OM"],
  ["Broche de défense","PC","OM"],
  ["Cadenas sournois","C","OM"],
  ["Canne de vétéran","C","OM"],
  ["Cape à la mode","C","OM"],
  ["Cape d'invisibilité","L","OM"],
  ["Cape de déplacement","R","OM"],
  ["Cape de l'arachnide","TR","OM"],
  ["Cape de la chauve-souris","R","OM"],
  ["Cape de la raie manta","PC","OM"],
  ["Cape de protection","PC","OM"],
  ["Cape de vol","R","OM"],
  ["Cape du prestidigitateur","R","OM"],
  ["Cape elfique","PC","OM"],
  ["Cape virevoltante","C","OM"],
  ["Capuchon de respiration aquatique","PC","OM"],
  ["Carafe intarissable","PC","OM"],
  ["Carillon d'ouverture","R","OM"],
  ["Carquois d'Ehlonna","PC","OM"],
  ["Cartes d'illusion","PC","OM"],
  ["Cartes merveilleuses","L","OM"],
  ["Ceinturon de force de géant","V","OM"],
  ["Ceinturon des nains","R","OM"],
  ["Chandelle des profondeurs","C","OM"],
  ["Chapeau de déguisement","PC","OM"],
  ["Chapeau de magicien","C","OM"],
  ["Chapeau de vermine","C","OM"],
  ["Chaussons de pattes d'araignée","PC","OM"],
  ["Chope de sobriété","C","OM"],
  ["Cierge d'invocation","TR","OM"],
  ["Clé mystérieuse","C","OM"],
  ["Colle universelle","L","OM"],
  ["Collier d'adaptation","PC","OM"],
  ["Collier de boules de feu","R","OM"],
  ["Collier de perles de prière","R","OM"],
  ["Cor de dévastation","R","OM"],
  ["Cor du Valhalla","R","OM"],
  ["Corde d'enchevêtrement","R","OM"],
  ["Corde d'escalade","PC","OM"],
  ["Corde réparable","C","OM"],
  ["Corne d'alarme silencieuse","C","OM"],
  ["Cornet acoustique","C","OM"],
  ["Cruche alchimique","PC","OM"],
  ["Cube de force","R","OM"],
  ["Cube des plans","L","OM"],
  ["Dé de charlatan","C","OM"],
  ["Diadème de destruction","PC","OM"],
  ["Encensoir de contrôle des élémentaires de l'air","R","OM"],
  ["Éventail enchanté","PC","OM"],
  ["Fers de rapidité","R","OM"],
  ["Fers de zéphyr","TR","OM"],
  ["Figurine merveilleuse","V","OM"],
  ["Flasque de fer","L","OM"],
  ["Flûte des égouts","PC","OM"],
  ["Flûte terrifiante","PC","OM"],
  ["Forteresse instantanée de Daern","R","OM"],
  ["Gantelets de puissance d'ogre","PC","OM"],
  ["Gants de chapardeur","PC","OM"],
  ["Gants de nage et d'escalade","PC","OM"],
  ["Gants piégeurs de projectiles","PC","OM"],
  ["Gemme d'illumination","PC","OM"],
  ["Gemme de vision","R","OM"],
  ["Gemme élémentaire","PC","OM"],
  ["Globe flottant","PC","OM"],
  ["Grimoire résistant","C","OM"],
  ["Havresac magique d'Hévard","R","OM"],
  ["Heaume de compréhension des langues","PC","OM"],
  ["Heaume de télépathie","PC","OM"],
  ["Heaume de téléportation","R","OM"],
  ["Heaume effrayant","C","OM"],
  ["Heaume scintillant","TR","OM"],
  ["Instrument à illusions","C","OM"],
  ["Instrument à message","C","OM"],
  ["Instrument de barde","V","OM"],
  ["Jatte de contrôle des élémentaires de l'eau","R","OM"],
  ["Lanterne de révélation","PC","OM"],
  ["Les Chapitres interdits","A","OM"],
  ["Les Chapitres sacrés","A","OM"],
  ["Liens de fer de Bilarro","R","OM"],
  ["Lunettes de nuit","PC","OM"],
  ["Manteau de résistance aux sorts","R","OM"],
  ["Manuel d'exercices physiques","TR","OM"],
  ["Manuel de vitalité","TR","OM"],
  ["Manuel de vivacité","TR","OM"],
  ["Manuel des golems","TR","OM"],
  ["Médaillon des pensées","PC","OM"],
  ["Menottes dimensionnelles","R","OM"],
  ["Miroir d'emprisonnement","TR","OM"],
  ["Oeil artificiel","C","OM"],
  ["Oeil et Main de Vecna","A","OM"],
  ["Orbe boussole","C","OM"],
  ["Orbe des dragons","A","OM"],
  ["Orbe horloge","C","OM"],
  ["Parfum envoûtant","C","OM"],
  ["Perche de pêcheur","C","OM"],
  ["Perche rétractable","C","OM"],
  ["Perle de force","R","OM"],
  ["Perle de pouvoir","PC","OM"],
  ["Perle désaltérante","C","OM"],
  ["Perle nutritive","C","OM"],
  ["Pierre de contrôle des élémentaires de la terre","R","OM"],
  ["Pierre de Ioun","V","OM"],
  ["Pierre porte-bonheur","PC","OM"],
  ["Pierres de communication à distance","PC","OM"],
  ["Pigments merveilleux de Nolzur","TR","OM"],
  ["Pipe des monstres de fumée","C","OM"],
  ["Plume de Quaal","R","OM"],
  ["Pot d'éveil","C","OM"],
  ["Poudre à éternuer","PC","OM"],
  ["Poupée qui parle","C","OM"],
  ["Poussière de disparition","PC","OM"],
  ["Poussière dessiccative","PC","OM"],
  ["Puits des mondes","L","OM"],
  ["Puits portable","R","OM"],
  ["Regard charmeur","PC","OM"],
  ["Robe aux étoiles","TR","OM"],
  ["Robe de camelot","PC","OM"],
  ["Robe de l'archimage","L","OM"],
  ["Robe de vision totale","R","OM"],
  ["Robe prismatique","TR","OM"],
  ["Rubis du mage de guerre","C","OM"],
  ["Sac à malices","PC","OM"],
  ["Sac de haricots","R","OM"],
  ["Sac dévoreur","TR","OM"],
  ["Sac sans fond","PC","OM"],
  ["Scarabée de protection","L","OM"],
  ["Selle du cavalier","PC","OM"],
  ["Solvant universel","L","OM"],
  ["Sphère d'annihilation","L","OM"],
  ["Submersible de Kwalish","L","OM"],
  ["Talisman de la sphère","L","OM"],
  ["Talisman du bien ultime","L","OM"],
  ["Talisman du mal absolu","L","OM"],
  ["Tapis volant","TR","OM"],
  ["Tome de la langue nouée","L","OM"],
  ["Traité d'autorité et d'influence","TR","OM"],
  ["Traité de compréhension","TR","OM"],
  ["Traité de perspicacité","TR","OM"],
  ["Vêtements raccommodeurs","C","OM"],
  ["Yeux de lynx","PC","OM"],
  ["Yeux grossissants","PC","OM"],
];

const ITEM_RARITIES = {
  C:  "Commun",
  PC: "Peu commun",
  R:  "Rare",
  TR: "Très rare",
  L:  "Légendaire",
  A:  "Artéfact",
  V:  "Variable",
};

const ITEM_RARITY_COLORS = {
  C:  "#9990a8",
  PC: "#22c55e",
  R:  "#3b82f6",
  TR: "#8b5cf6",
  L:  "#c9a227",
  A:  "#ef4444",
  V:  "#9990a8",
};

const ITEM_TYPES = {
  ARM: "Armure",
  ARW: "Arme",
  BAG: "Baguette",
  BAT: "Bâton",
  SCE: "Sceptre",
  ANN: "Anneau",
  OM:  "Obj. merveilleux",
  POT: "Potion",
  PAR: "Parchemin",
};
