// Poids des objets D&D 5e (en kg) — source : aidedd.org
// Utilisé pour l'affichage dans les tooltips et le calcul d'encombrement
const ITEMS_WEIGHT = {
  'acide (fiole)': 0.5,
  'aiguilles de sarbacane (50)': 0.5,
  'amulette': 0.5,
  'arbalète de poing': 1.5,
  'arbalète lourde': 9.0,
  'arbalète légère': 2.5,
  'arc court': 1.0,
  'arc long': 1.0,
  'baguette': 0.5,
  "baguette d'if": 0.5,
  'balance de marchand': 1.5,
  'billes (sac de 1000)': 1.0,
  'billes de fronde (20)': 0.75,
  "boite d'allume-feu": 0.5,
  'bouclier': 3.0,
  'boule de cristal': 0.5,
  'boulier': 1.0,
  'bouteille en verre': 1.0,
  'broigne': 20.0,
  'bâton': 2.0,
  'bélier portable': 17.5,
  'cadenas': 0.5,
  'carquois': 0.5,
  'carreau': 0.75,
  "carreaux d'arbalète (20)": 0.75,
  'chausse-trappes (sac de 20)': 1.0,
  'chaîne (3 m)': 5.0,
  'chemise de mailles': 10.0,
  'cimeterre': 1.5,
  'clibanion': 30.0,
  'coffre': 12.5,
  'corde': 5.0,
  'corde en chanvre (15 m)': 5.0,
  'corde en soie (15 m)': 2.5,
  'cotte de mailles': 27.5,
  'coutille': 3.0,
  'couverture': 1.5,
  'cruche ou pichet': 2.0,
  'cuir': 5.0,
  'cuir clouté': 6.5,
  'cuirasse': 10.0,
  'dague': 0.5,
  'demi-plate': 20.0,
  'eau bénite (flasque)': 0.5,
  'feu grégeois (flasque)': 0.5,
  'filet': 1.5,
  'flasque ou chope (50 cl)': 0.5,
  'flèche': 0.5,
  'flèches (20)': 0.5,
  "fléau d'armes": 1.0,
  'fléchette': 0.1,
  'fouet': 1.5,
  'gamelle': 0.5,
  'gourde (pleine)': 2.5,
  'gourdin': 1.0,
  'grappin': 2.0,
  'grimoire': 1.5,
  "hache d'armes": 2.0,
  'hache à deux mains': 3.5,
  'hachette': 1.0,
  'hallebarde': 3.0,
  'harnois': 32.5,
  'huile (flasque)': 0.5,
  'javeline': 1.0,
  "kit d'escalade": 6.0,
  'lampe': 0.5,
  'lance': 1.5,
  "lance d'arçon": 3.0,
  'lanterne sourde': 1.0,
  'lanterne à capote': 1.0,
  'livre': 2.5,
  'longue-vue': 0.5,
  'maillet': 5.0,
  'marteau': 1.5,
  'marteau de forgeron': 5.0,
  'marteau de guerre': 1.0,
  'marteau léger': 1.0,
  "masse d'armes": 2.0,
  'massue': 5.0,
  'matelassée': 4.0,
  'matériel de pêche': 2.0,
  'menottes': 3.0,
  'miroir en acier': 0.25,
  'morgenstern': 2.0,
  'orbe': 1.5,
  'palan': 2.5,
  'panier': 1.0,
  'peaux': 6.0,
  'pelle': 2.5,
  'perche (3 m)': 3.5,
  'pic de guerre': 1.0,
  'pied-de-biche': 2.5,
  'pierre à aiguiser': 0.5,
  'pioche de mineur': 5.0,
  'pique': 9.0,
  'piton': 0.12,
  'piège à mâchoires': 12.5,
  'pointes en fer (10)': 2.5,
  'pot en fer': 5.0,
  'potion de guérison': 0.25,
  'potion de soin': 0.25,
  'rapière': 1.0,
  'rations (1 jour)': 1.0,
  'reliquaire': 1.0,
  'robes': 2.0,
  'sablier': 0.5,
  'sac': 0.25,
  'sac de couchage': 3.5,
  'sac à dos': 2.5,
  'sacoche': 0.5,
  'sacoche à composantes': 1.0,
  'sarbacane': 0.5,
  'sceptre': 1.0,
  'seau': 1.0,
  'serpe': 1.0,
  'tente': 10.0,
  'tonneau': 35.0,
  'torche': 0.5,
  'torches': 0.5,
  'trident': 2.0,
  'trousse de soins': 1.5,
  'vêtements, communs': 1.5,
  'vêtements, costume': 2.0,
  'vêtements, fins': 3.0,
  'vêtements, voyage': 2.0,
  'écailles': 22.5,
  'échelle (3 m)': 12.5,
  'épée courte': 1.0,
  'épée longue': 1.5,
  'épée à deux mains': 3.0,
  'étui à carreaux': 0.5,
  'étui à cartes ou parchemins': 0.5,
};