// Partagé entre game.html et lobby.html
// ══════════════════════════════════════════════════════════════
const SPELLS_DB = [
  // ── Niveau 0 ─────────────────────────────────────────────
  ["Aspersion acide",0,"Invo","ME"],
  ["Bouffée de poison",0,"Invo","DEMO"],
  ["Coup au but",0,"Div","B"],
  ["Coup de tonnerre",0,"Évoc","BE"],
  ["Druidisme",0,"Tran","D"],
  ["Flamme sacrée",0,"Évoc","C"],
  ["Glas funèbre",0,"Nécr","BC"],
  ["Illusion mineure",0,"Illu","BEMO"],
  ["Lance de feu",0,"Évoc","DE"],
  ["Lumière",0,"Évoc","BCM"],
  ["Lumières dansantes",0,"Évoc","BEM"],
  ["Main du mage",0,"Invo","BEM"],
  ["Message",0,"Tran","BEM"],
  ["Mot de radiance",0,"Évoc","C"],
  ["Prestidigitation",0,"Tran","BEMO"],
  ["Rayon de givre",0,"Évoc","EMO"],
  ["Rayon de lune",0,"Tran","D"],
  ["Réparation",0,"Tran","BCDM"],
  ["Résistance",0,"Abj","CD"],
  ["Sauvagerie primitive",0,"Invo","D"],
  ["Shillelagh",0,"Tran","D"],
  ["Sort mineur de l'occulte",0,"Ench","O"],
  ["Thaumaturgie",0,"Tran","C"],
  ["Trait de feu",0,"Évoc","M"],
  ["Trait de givre",0,"Évoc","EM"],
  ["Trait empoisonné",0,"Nécr","O"],
  ["Trait mental",0,"Ench","BEM"],
  ["Verbe de tonnerre",0,"Évoc","B"],
  ["Aiguille venimeuse",0,"Nécr","MO"],
  ["Contact glacial",0,"Nécr","MO"],
  ["Coup de fouet épineux",0,"Invo","D"],
  ["Décharge occulte",0,"Évoc","O"],
  ["Épargne des mourants",0,"Nécr","CD"],
  // ── Niveau 1 ─────────────────────────────────────────────
  ["Alarme",1,"Abj","MR"],
  ["Armure du mage",1,"Abj","ME"],
  ["Bénédiction",1,"Ench","CP"],
  ["Bouclier",1,"Abj","M"],
  ["Bouclier de la foi",1,"Abj","CP"],
  ["Charme-personne",1,"Ench","BDEMO"],
  ["Châtiment courroucé",1,"Évoc","P"],
  ["Châtiment révélateur",1,"Div","P"],
  ["Couleurs giclantes",1,"Illu","ME"],
  ["Corde enchantée",1,"Tran","M"],
  ["Détection de la magie",1,"Div","BCDMPR"],
  ["Détection du mal et du bien",1,"Div","CP"],
  ["Détection du poison et des maladies",1,"Div","CDPR"],
  ["Feuille morte",1,"Tran","D"],
  ["Fléau",1,"Ench","BC"],
  ["Foulée de tonnerre",1,"Invo","BE"],
  ["Graisse",1,"Invo","M"],
  ["Grande foulée",1,"Tran","BDEM"],
  ["Grêle d'épines",1,"Invo","R"],
  ["Identification",1,"Div","BM"],
  ["Image silencieuse",1,"Illu","BEM"],
  ["Injonction",1,"Ench","CP"],
  ["Lien protecteur",1,"Abj","CP"],
  ["Lueurs féeriques",1,"Évoc","BD"],
  ["Mains brûlantes",1,"Évoc","ME"],
  ["Marque du chasseur",1,"Div","R"],
  ["Missile magique",1,"Évoc","ME"],
  ["Mot de guérison",1,"Évoc","BCD"],
  ["Nappe de brouillard",1,"Invo","CDR"],
  ["Projectile enflammé",1,"Évoc","M"],
  ["Protection contre le mal et le bien",1,"Abj","BCDMOP"],
  ["Purification de la nourriture et de l'eau",1,"Tran","CDP"],
  ["Sanctuaire",1,"Abj","C"],
  ["Saut",1,"Tran","DR"],
  ["Soin des blessures",1,"Évoc","BCDPR"],
  ["Sommeil",1,"Ench","BDEMO"],
  ["Souffle des dieux",1,"Invo","D"],
  ["Texte illusoire",1,"Illu","BM"],
  ["Trait de foudre",1,"Évoc","M"],
  ["Vague tonnante",1,"Évoc","BDE"],
  ["Baies nourricières",1,"Tran","D"],
  ["Bras de Hadar",1,"Invo","O"],
  ["Compréhension des langues",1,"Div","BEMO"],
  ["Couverture de neige",1,"Invo","DR"],
  ["Détection des pensées",1,"Div","BEM"],
  ["Duel contraignant",1,"Ench","P"],
  ["Frappe courroucée",1,"Évoc","P"],
  ["Frappe empoisonnée",1,"Invo","P"],
  ["Frappe tonnante",1,"Tran","P"],
  ["Héroïsme",1,"Ench","BP"],
  ["Nappe huileuse",1,"Invo","M"],
  ["Repli expéditieux",1,"Tran","ME"],
  ["Serviteur invisible",1,"Invo","BM"],
  ["Sorts de soin de la blessure",1,"Évoc","BCDPR"],
  // ── Niveau 2 ─────────────────────────────────────────────
  ["Agrandir/Rétrécir",2,"Tran","ME"],
  ["Arme magique",2,"Tran","MP"],
  ["Aide",2,"Ench","CP"],
  ["Aveuglément/Surdité",2,"Nécr","BCE"],
  ["Bouche magique",2,"Illu","BM"],
  ["Brise-fer",2,"Tran","D"],
  ["Calme des émotions",2,"Ench","BC"],
  ["Cécité/Surdité",2,"Nécr","BCE"],
  ["Chaînes de la Géhenne",2,"Invo","O"],
  ["Cœur de ténèbres",2,"Nécr","O"],
  ["Détection des pièges",2,"Div","CDR"],
  ["Détection de l'invisibilité",2,"Div","BEMO"],
  ["Flamme éternelle",2,"Évoc","CM"],
  ["Flèche acide de Melf",2,"Évoc","M"],
  ["Force de taureau",2,"Tran","BCDMPR"],
  ["Fracas",2,"Évoc","BEM"],
  ["Immobiliser un humanoïde",2,"Ench","BCMOP"],
  ["Lévitation",2,"Tran","ME"],
  ["Lumière du jour",2,"Évoc","CDR"],
  ["Métal brûlant",2,"Tran","D"],
  ["Modification d'apparence",2,"Tran","ME"],
  ["Mot de ralliement",2,"Évoc","B"],
  ["Noirceur",2,"Évoc","MO"],
  ["Nuage de lames",2,"Invo","B"],
  ["Pas brumeux",2,"Invo","BEMP"],
  ["Prière de guérison",2,"Évoc","C"],
  ["Porte-voix",2,"Tran","B"],
  ["Protection contre le poison",2,"Abj","CDPR"],
  ["Protection contre les projectiles",2,"Abj","M"],
  ["Rayon affaiblissant",2,"Nécr","M"],
  ["Rayon de lune",2,"Évoc","D"],
  ["Restauration partielle",2,"Abj","BCP"],
  ["Silence",2,"Illu","BCR"],
  ["Sort de la porte des ombres",2,"Illu","O"],
  ["Toile d'araignée",2,"Invo","ME"],
  ["Verrou magique",2,"Abj","M"],
  ["Vision dans le noir",2,"Tran","DEMR"],
  ["Zones de vérité",2,"Ench","CP"],
  ["Convocation d'animaux",2,"Invo","DR"],
  ["Détection des pensées",2,"Div","BEM"],
  ["Frappe de foudre",2,"Évoc","DP"],
  ["Liens ensorcelants",2,"Invo","B"],
  ["Porte de l'ombre",2,"Illu","O"],
  ["Suggestion",2,"Ench","BEMO"],
  // ── Niveau 3 ─────────────────────────────────────────────
  ["Animisme",3,"Nécr","CD"],
  ["Apaisement des émotions",3,"Ench","BC"],
  ["Appel de la foudre",3,"Invo","D"],
  ["Boule de feu",3,"Évoc","ME"],
  ["Cercle magique",3,"Abj","CMOP"],
  ["Clairvoyance",3,"Div","BCM"],
  ["Communication avec les morts",3,"Nécr","B"],
  ["Contresort",3,"Abj","MEO"],
  ["Convocation d'animaux",3,"Invo","DR"],
  ["Création de nourriture et d'eau",3,"Invo","CP"],
  ["Croissance végétale",3,"Tran","DR"],
  ["Debout les morts !",3,"Nécr","C"],
  ["Dissipation de la magie",3,"Abj","BCDMOP"],
  ["Éclair",3,"Évoc","ME"],
  ["Espoir dévastateur",3,"Ench","B"],
  ["État cadavérique",3,"Nécr","CM"],
  ["Forme gazeuse",3,"Tran","MEO"],
  ["Glyphe de protection",3,"Abj","BCM"],
  ["Grande image",3,"Illu","BDEM"],
  ["Hâte",3,"Tran","ME"],
  ["Image majeure",3,"Illu","BDEM"],
  ["Langue des bêtes",3,"Tran","BDR"],
  ["Lenteur",3,"Tran","ME"],
  ["Lumière du jour",3,"Évoc","CDR"],
  ["Malédiction",3,"Nécr","BCP"],
  ["Marche sur l'eau",3,"Tran","CDP"],
  ["Mot de puissance : Guérison",3,"Ench","B"],
  ["Mur de vent",3,"Évoc","DR"],
  ["Protection contre l'énergie",3,"Abj","CDMPR"],
  ["Respiration aquatique",3,"Tran","BDMR"],
  ["Revigoration",3,"Tran","CD"],
  ["Semonce",3,"Ench","P"],
  ["Soins importants",3,"Évoc","BCDP"],
  ["Souffle du dragon",3,"Tran","ME"],
  ["Tempête de neige",3,"Invo","BDM"],
  ["Terreur",3,"Illu","BCMO"],
  ["Trait de foudre",3,"Évoc","ME"],
  ["Vol",3,"Tran","ME"],
  ["Convocation de démons mineurs",3,"Invo","O"],
  ["Flèches enflammées",3,"Tran","DR"],
  ["Frappe de géant des tempêtes",3,"Évoc","P"],
  ["Mur de sable",3,"Tran","DM"],
  ["Mot de puissance douleur",3,"Ench","BE"],
  // ── Niveau 4 ─────────────────────────────────────────────
  ["Arcane œil",4,"Div","M"],
  ["Assassin fantôme",4,"Illu","M"],
  ["Banissement",4,"Abj","BCMOP"],
  ["Bénédiction de la dryade",4,"Ench","D"],
  ["Confusion",4,"Ench","BDMO"],
  ["Construction de demi-plan",4,"Invo","BM"],
  ["Contrôle de l'eau",4,"Tran","BCDM"],
  ["Fabrication",4,"Tran","M"],
  ["Fidèle animal de compagnie",4,"Invo","R"],
  ["Flétrissure",4,"Nécr","CO"],
  ["Forme élémentaire",4,"Tran","D"],
  ["Gardien de la foi",4,"Invo","C"],
  ["Guérison de groupe",4,"Évoc","BCDP"],
  ["Liberté de mouvement",4,"Abj","BDCPR"],
  ["Localiser une créature",4,"Div","BCDMPR"],
  ["Porte dimensionnelle",4,"Invo","BEMO"],
  ["Résistance aux éléments",4,"Abj","DP"],
  ["Tempête de grêle",4,"Évoc","BDM"],
  ["Terrain hallucinatoire",4,"Illu","BDM"],
  ["Invisibilité supérieure",4,"Illu","BE"],
  ["Mur de feu",4,"Évoc","DEM"],
  ["Sphère de feu",4,"Invo","DM"],
  // ── Niveau 5 ─────────────────────────────────────────────
  ["Animation des morts",5,"Nécr","CM"],
  ["Cercle de puissance",5,"Abj","P"],
  ["Cône de froid",5,"Évoc","EMO"],
  ["Contactez les autres plans",5,"Div","M"],
  ["Contrôle des vents",5,"Tran","D"],
  ["Destruction des morts-vivants",5,"Nécr","C"],
  ["Dissipation du mal et du bien",5,"Abj","CP"],
  ["Domination de personne",5,"Ench","BCMO"],
  ["Flamme sacrée",5,"Évoc","P"],
  ["Fléau des insectes",5,"Invo","CD"],
  ["Guérison de groupe",5,"Évoc","BCDP"],
  ["Immobiliser un monstre",5,"Ench","BEMOP"],
  ["Légendaire",5,"Tran","B"],
  ["Mur de pierre",5,"Évoc","DM"],
  ["Nuée de météores",5,"Évoc","M"],
  ["Passe-muraille",5,"Tran","M"],
  ["Plaie",5,"Nécr","CM"],
  ["Rappel à la vie",5,"Nécr","BCP"],
  ["Scrutation",5,"Div","BCDMOP"],
  ["Sphère de force",5,"Évoc","ME"],
  ["Symbole",5,"Abj","BCM"],
  ["Télékinésie",5,"Tran","ME"],
  ["Téléportation",5,"Invo","BEMO"],
  ["Transformation du rocher",5,"Tran","DM"],
  ["Vision véritable",5,"Div","BCM"],
  // ── Niveau 6 ─────────────────────────────────────────────
  ["Anneau de la tempête",6,"Invo","D"],
  ["Cercle de mort",6,"Nécr","OM"],
  ["Chair de pierre",6,"Tran","DM"],
  ["Contamination",6,"Nécr","D"],
  ["Contingence",6,"Évoc","M"],
  ["Création de mort-vivant",6,"Nécr","CM"],
  ["Désintégration",6,"Tran","ME"],
  ["Festin des héros",6,"Invo","CD"],
  ["Forme de nuage",6,"Tran","D"],
  ["Globe d'invulnérabilité",6,"Abj","ME"],
  ["Guérison",6,"Évoc","CD"],
  ["Illusion programmatique",6,"Illu","BM"],
  ["Inondation",6,"Invo","D"],
  ["Lumière du soleil",6,"Évoc","BDM"],
  ["Suggestion de groupe",6,"Ench","BEMO"],
  ["Transport via les plantes",6,"Invo","D"],
  ["Trouver le chemin",6,"Div","BCD"],
  ["Vrai voir",6,"Div","BCM"],
  ["Mur de glace",6,"Évoc","DM"],
  ["Mur de pics",6,"Invo","M"],
  // ── Niveau 7 ─────────────────────────────────────────────
  ["Cage de force",7,"Évoc","M"],
  ["Changement de plan",7,"Invo","BCDMOP"],
  ["Déluge de météores",7,"Évoc","ME"],
  ["Doigt de mort",7,"Nécr","MO"],
  ["Forme éthérée",7,"Tran","BCMO"],
  ["Frappe de tempête de feu",7,"Évoc","D"],
  ["Image projetée",7,"Illu","BEM"],
  ["Inversion de la gravité",7,"Tran","DEM"],
  ["Mirage arcanique",7,"Illu","BDM"],
  ["Mot de pouvoir : Douleur",7,"Ench","BE"],
  ["Muraille de feu",7,"Évoc","D"],
  ["Régénération",7,"Tran","BCD"],
  ["Résurrection",7,"Nécr","BCP"],
  ["Séquestre",7,"Tran","M"],
  ["Symbole",7,"Abj","BCM"],
  ["Téléportation de groupe",7,"Invo","M"],
  // ── Niveau 8 ─────────────────────────────────────────────
  ["Antimagie",8,"Abj","CM"],
  ["Clone",8,"Nécr","M"],
  ["Contrôle des conditions climatiques",8,"Tran","CD"],
  ["Domination de monstre",8,"Ench","BE"],
  ["Esprit de mort",8,"Nécr","O"],
  ["Fléau de la nature",8,"Nécr","D"],
  ["Incroyable téléportation",8,"Invo","M"],
  ["Mot de pouvoir : Étourdissement",8,"Ench","BME"],
  ["Nuée de météores",8,"Évoc","ME"],
  ["Séisme",8,"Évoc","CD"],
  ["Sphère de puissance",8,"Abj","BM"],
  ["Sunburst",8,"Évoc","DM"],
  // ── Niveau 9 ─────────────────────────────────────────────
  ["Arrêt du temps",9,"Tran","ME"],
  ["Châtiment béatifique",9,"Évoc","P"],
  ["Frappe d'astral",9,"Tran","D"],
  ["Forteresse du demi-plan",9,"Invo","M"],
  ["Mot de pouvoir : Mort",9,"Ench","BEMO"],
  ["Métamorphose totale",9,"Tran","M"],
  ["Nuée de météores",9,"Évoc","ME"],
  ["Portail",9,"Invo","CMP"],
  ["Prémonition",9,"Div","BDMO"],
  ["Résurrection véritable",9,"Nécr","BCP"],
  ["Souhaiter",9,"Invo","ME"],
  ["Tempête de vengeance",9,"Invo","D"],
  ["Tissage des âmes",9,"Nécr","C"],
];

const SP_CLASSES = ['B','C','D','E','M','O','P','R'];
const SP_CLASS_NAMES = {B:'Barde',C:'Clerc',D:'Druide',E:'Ensorceleur',M:'Magicien',O:'Occultiste',P:'Paladin',R:'Rôdeur'};
const SP_SCHOOL_NAMES = {Abj:'Abjuration',Invo:'Invocation',Div:'Divination',Ench:'Enchantement',Évoc:'Évocation',Illu:'Illusion',Nécr:'Nécromancie',Tran:'Transmutation'};

// Dés de chaque sort  — format "type:dés"
// type : atk = jet d'attaque de sort + dégâts  |  sav = jet de sauvegarde + dégâts
//        heal = soins  |  hit = dégâts automatiques (pas de jet d'attaque)
// Les sorts utilitaires (sans dés) sont absents du tableau.
const SPELLS_DICE = {
  // ── Cantrips (niveau 0) ────────────────────────────────────
  "Aspersion acide":           "sav:1d6",
  "Bouffée de poison":         "sav:1d12",
  "Coup de tonnerre":          "sav:1d6",
  "Flamme sacrée":             "sav:1d8",
  "Glas funèbre":              "sav:1d12",
  "Lance de feu":              "atk:1d8",
  "Mot de radiance":           "sav:1d6",
  "Rayon de givre":            "atk:1d8",
  "Sauvagerie primitive":      "atk:1d10",
  "Sort mineur de l'occulte":  "atk:1d10",
  "Trait de feu":              "atk:1d10",
  "Trait de givre":            "atk:1d8",
  "Trait empoisonné":          "sav:1d12",
  "Trait mental":              "sav:1d6",
  "Verbe de tonnerre":         "sav:1d4",
  "Aiguille venimeuse":        "atk:1d4",
  "Contact glacial":           "atk:1d8",
  "Coup de fouet épineux":     "atk:1d6",
  "Décharge occulte":          "atk:1d10",
  // ── Niveau 1 ──────────────────────────────────────────────
  "Châtiment courroucé":       "atk:1d6",
  "Châtiment révélateur":      "atk:1d6",
  "Foulée de tonnerre":        "sav:2d8",
  "Grêle d'épines":            "atk:1d10",
  "Mains brûlantes":           "sav:3d6",
  "Missile magique":           "hit:3d4",
  "Mot de guérison":           "heal:1d4",
  "Projectile enflammé":       "atk:3d8",
  "Soin des blessures":        "heal:1d8",
  "Sorts de soin de la blessure": "heal:1d8",
  "Trait de foudre":           "atk:1d12",
  "Vague tonnante":            "sav:2d8",
  "Bras de Hadar":             "sav:2d6",
  "Couverture de neige":       "atk:1d10",
  "Frappe courroucée":         "atk:1d6",
  "Frappe empoisonnée":        "sav:2d6",
  "Frappe tonnante":           "atk:2d6",
  // ── Niveau 2 ──────────────────────────────────────────────
  "Brise-fer":                 "sav:3d8",
  "Flèche acide de Melf":      "atk:4d4",
  "Fracas":                    "sav:3d8",
  "Métal brûlant":             "sav:2d8",
  "Mot de ralliement":         "heal:2d8",
  "Nuage de lames":            "sav:4d4",
  "Prière de guérison":        "heal:2d8",
  "Rayon affaiblissant":       "atk:2d6",
  "Rayon de lune":             "sav:2d10",
  "Frappe de foudre":          "atk:2d8",
  // ── Niveau 3 ──────────────────────────────────────────────
  "Appel de la foudre":        "sav:3d10",
  "Boule de feu":              "sav:8d6",
  "Éclair":                    "sav:8d6",
  "Soins importants":          "heal:3d8",
  "Souffle du dragon":         "sav:3d6",
  "Frappe de géant des tempêtes": "atk:4d8",
  // ── Niveau 4 ──────────────────────────────────────────────
  "Assassin fantôme":          "sav:4d10",
  "Flétrissure":               "sav:8d8",
  "Gardien de la foi":         "sav:4d6",
  "Guérison de groupe":        "heal:4d8",
  "Mur de feu":                "sav:4d8",
  "Sphère de feu":             "sav:2d6",
  "Tempête de grêle":          "sav:4d8",
  // ── Niveau 5 ──────────────────────────────────────────────
  "Cône de froid":             "sav:8d8",
  "Fléau des insectes":        "sav:4d10",
  "Plaie":                     "sav:8d8",
  // ── Niveau 6 ──────────────────────────────────────────────
  "Anneau de la tempête":      "sav:6d8",
  "Cercle de mort":            "sav:8d6",
  "Désintégration":            "atk:10d6",
  "Inondation":                "sav:6d8",
  "Lumière du soleil":         "sav:6d8",
  "Mur de glace":              "sav:6d6",
  "Mur de pics":               "atk:4d10",
  // ── Niveau 7 ──────────────────────────────────────────────
  "Déluge de météores":        "sav:7d10",
  "Doigt de mort":             "sav:7d8",
  "Frappe de tempête de feu":  "sav:7d10",
  "Muraille de feu":           "sav:7d8",
  // ── Niveau 8 ──────────────────────────────────────────────
  "Fléau de la nature":        "sav:12d8",
  "Nuée de météores":          "sav:20d6",
  "Sunburst":                  "sav:12d6",
  // ── Niveau 9 ──────────────────────────────────────────────
  "Châtiment béatifique":      "atk:9d8",
  "Tempête de vengeance":      "sav:10d6",
};

